package vending.protocol;

public enum MessageType {
    SALE,
    STOCK,
    STOCK_ALERT,
    RESTOCK,
    DRINK_UPDATE,
    COLLECT,
    SYNC,
    HEARTBEAT,
    HEARTBEAT_ACK,
    ACTIVE_SERVER,
    QUERY_ALERTS,
    QUERY_SALES,
    ALERT_LIST,
    SALES_SUMMARY,
    REMOTE_DRINK_SET,
    REMOTE_DRINK_UPDATE,
    QUERY_REMOTE,
    REMOTE_COMMAND_LIST,
    SNAPSHOT_REQUEST,
    SNAPSHOT,
    ERROR
}
